-- 1. 테이블 생성
create table if not exists public.math_worm_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  class_name smallint not null check (class_name between 1 and 6),
  number smallint not null check (number between 1 and 30),
  nickname text not null check (char_length(nickname) between 1 and 20),
  score integer not null check (score >= 0)
);

-- 2. 성능 향상을 위한 인덱스 생성
create index if not exists math_worm_scores_score_idx on public.math_worm_scores (score desc);
create index if not exists math_worm_scores_class_name_score_idx on public.math_worm_scores (class_name, score desc);

-- 3. Row Level Security (RLS) 활성화
alter table public.math_worm_scores enable row level security;

-- 4. 정책 설정 (익명 사용자의 데이터 삽입 및 조회 허용)
drop policy if exists "Allow anonymous inserts" on public.math_worm_scores;
create policy "Allow anonymous inserts"
  on public.math_worm_scores
  for insert
  with check (true);

drop policy if exists "Allow anonymous selects" on public.math_worm_scores;
create policy "Allow anonymous selects"
  on public.math_worm_scores
  for select
  using (true);

-- 5. 프로필 테이블 생성 (Phase 3)
create table if not exists public.profiles (
  student_id text primary key,
  created_at timestamptz default now() not null,
  password text not null,
  dragon_type text not null,
  personality text[] not null,
  job_group text not null,
  level integer default 1,
  exp integer default 0
);

-- 6. 프로필 테이블 RLS 활성화 및 정책 설정
alter table public.profiles enable row level security;

drop policy if exists "Allow anonymous inserts profiles" on public.profiles;
create policy "Allow anonymous inserts profiles"
  on public.profiles
  for insert
  with check (true);

drop policy if exists "Allow anonymous selects profiles" on public.profiles;
create policy "Allow anonymous selects profiles"
  on public.profiles
  for select
  using (true);
